//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Load3Window
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OneTableMuchEntities : DbContext
    {
        public static OneTableMuchEntities _context;
        public static OneTableMuchEntities GetContext()
        {
            if (_context == null)
                _context = new OneTableMuchEntities();
            return _context;
        }
        public OneTableMuchEntities()
            : base("name=OneTableMuchEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MuchTable> MuchTable { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
