//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Load3Window
{
    using System;
    using System.Collections.Generic;
    
    public partial class MuchTable
    {
        public int id { get; set; }
        public string At1 { get; set; }
        public string At2 { get; set; }
        public int At3 { get; set; }
        public int At4 { get; set; }
        public int at5 { get; set; }
        public int at6 { get; set; }
        public int at7 { get; set; }
        public int at8 { get; set; }
        public int at9 { get; set; }
        public int at10 { get; set; }
        public int at11 { get; set; }
        public int at12 { get; set; }
        public int at13 { get; set; }
    }
}
